"""Constants."""

HTTP_TIMEOUT = 15
TIMEZONE = 'Asia/Kolkata'

STATUS_CODE_403 = 403

CIRCUIT_BREAKER_RETRY = 5
CIRCUIT_BREAKER_TIMEOUT = 60
CIRCUIT_BREAKER_DELAY = 0
CIRCUIT_BREAKER_MAX_DELAY = 0
CHUNK_SIZE_CONSTANT = 1024
